apply plugin: 'com.android.library'

android {
    namespace = "me.teble.xposed.stub"
    compileSdk = 32
    enableKotlin = false
    defaultConfig {
        minSdk = 21
    }
    lint {
        abortOnError = false
    }

    dependencies {
        // androidx nullability stubs
        compileOnly("androidx.annotation:annotation:1.6.0")
        compileOnly(libs.androidx.lifecycle.common)
    }
}
